postgres:
    container_name: clair_postgres
    image: postgres:9
    environment:
      POSTGRES_PASSWORD: password

clair:
    container_name: clair_clair
    image: cargo.caicloud.io/caicloud/clair:v1.2.3
    ports:
        - "6060-6061:6060-6061"
    expose:
        - "6060-6061"
    links:
        - postgres
    volumes:
        - /tmp:/tmp
        - ./scripts/clair_config:/config
    command: [-config, /config/config.yaml]

zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
        - "2181"

kafka:
    image: wurstmeister/kafka:0.10.1.0
    hostname: kafka
    links:
        - zookeeper:zk
    volumes:
       - /data/kafka_log:/data/kafka_log
    environment:
        - KAFKA_ADVERTISED_HOST_NAME=0.0.0.0
        - KAFKA_ADVERTISED_PORT=9092
        - KAFKA_LOG_DIRS=/data/kafka_log
    ports:
        - "9092:9092"
    expose:
        - "9092"
etcd:
    image: cargo.caicloud.io/caicloud/etcd:v2.2.1
    ports:
        - "2379:2379"
        - "2380:2380"
        - "4001:4001"
        - "7001:7001"
    environment:
        - name=etcd-server
        - advertise-client-urls=http://0.0.0.0:4001
        - initial-advertise-peer-urls=http://0.0.0.0:7001

mongo:
    image: mongo:3.0.5
    ports:
        - "28017:27017"
    command: mongod --smallfiles
