apiVersion: v1
kind: Service
metadata:
  name: clairsvc
  labels:
    name: clairsvc
  namespace: cyclone
spec:
  type: NodePort
  ports:
  - port: 6060
    protocol: TCP
    nodePort: 30060
    name: clair-port0
  - port: 6061
    protocol: TCP
    nodePort: 30061
    name: clair-port1
  selector:
    name: clairsvc
    