apiVersion: v1
kind: Service
metadata:
  labels:
    name: etcd-server
  name: etcd-server
  namespace: cyclone
spec:
  ports:
  - port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    name: etcd-server
  sessionAffinity: None
  type: ClusterIP
  