apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: kafka-server
  name: kafka-server
  namespace: cyclone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: kafka-server
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-server
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-server:2181
        - name: KAFKA_LOG_DIRS
          value: /data
        image: cargo.caicloud.io/caicloud/kafka:0.10.1.0
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
        - containerPort: 9092
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
           - mountPath: /data
             name: data
      volumes:
         - name: data
           nfs:
             path: /cyclone-kafka
             server: 10.254.0.110
      dnsPolicy: ClusterFirst
      securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30