apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: mongo-server
  name: mongo-server
  namespace: cyclone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: mongo-server
    spec:
      containers:
      - args:
        - --smallfiles
        command:
        - mongod
        image: cargo.caicloud.io/caicloud/mongo:3.0.5
        imagePullPolicy: IfNotPresent
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
           - mountPath: /data/db
             name: data
      volumes:
         - name: data
           nfs:
             path: /cyclone-mongo
             server: 10.254.0.110 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      