apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo-server
  name: mongo-server
  namespace: cyclone
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongo-server
  sessionAffinity: None
  type: ClusterIP
  