apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: zookeeper-server
  name: zookeeper-server
  namespace: cyclone
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: zookeeper-server
    spec:
      containers:
      - env:
        - name: SERVER_ID
          value: "1"
        - name: MAX_SERVERS
          value: "1"
        - name: ZOOKEEPER_MEMBER
          value: zookeeper-server
        image: cargo.caicloud.io/caicloud/zookeeper:3.4.6
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2181
          protocol: TCP
        - containerPort: 2888
          protocol: TCP
        - containerPort: 3888
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      