apiVersion: v1
kind: Service
metadata:
  labels:
    name: zookeeper-server
  name: zookeeper-server
  namespace: cyclone
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: followers
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: election
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    name: zookeeper-server
  sessionAffinity: None
  type: ClusterIP
  